services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,DataFixtures,Command}'
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Command\:
        resource: '../../src/AppBundle/Command/*'
        tags: ['console.command']

    Elasticsearch\ClientBuilder:
        factory: ['Elasticsearch\ClientBuilder', 'create']

    AppBundle\Service\ElasticSearch:
        arguments:
            $host: "%elasticsearch_host%"
            $indexName: "%elasticsearch_index_name%"
        tags:
            - { name: monolog.logger, channel: elasticsearch }

    AppBundle\Service\AffiliateLinkHandler:
        arguments:
            $affiliateMappings: '%affiliate_mappings%'
            $cache: '@Symfony\Component\Cache\Simple\Psr6Cache'

    AppBundle\Listener\SearchIndexUpdater:
        arguments:
            $environment: "%kernel.environment%"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    AppBundle\Form\Extension\HelpTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    AppBundle\Listener\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    AppBundle\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 999 }

    # TODO: Remove this service once we update to Symfony 4.1
    # and set the $cache argument of the AppBundle\Twig\AppExtension
    # to '@cache.app.simple'
    #
    # see https://github.com/symfony/symfony/pull/25710
    Symfony\Component\Cache\Simple\Psr6Cache:
        arguments: ['@cache.app']

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        # For some reason the translation doesn't work if we autowire this service.
        autowire: false
        tags:
            - { name: twig.extension }
